### ISSUE TITLE
Certificate verify failed

### ISSUE THREAD

**Issue by halimB8** [stormshield/python-SNS-API#4]
Hello,

It's my first time trying to send a rule from a remote host to my freiwall and I am getting this error 
 
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/urllib3/connectionpool.py", line 597, in urlopen
    httplib_response = self._make_request(conn, method, url,
  File "/usr/local/lib/python3.8/dist-packages/urllib3/connectionpool.py", line 343, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.8/dist-packages/urllib3/connectionpool.py", line 849, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.8/dist-packages/urllib3/connection.py", line 349, in connect
    self.sock = ssl_wrap_socket(
  File "/usr/local/lib/python3.8/dist-packages/urllib3/util/ssl_.py", line 372, in ssl_wrap_socket
    return context.wrap_socket(sock)
  File "/usr/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/usr/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/usr/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1123)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/.local/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.8/dist-packages/urllib3/connectionpool.py", line 637, in urlopen
    retries = retries.increment(method, url, error=e, _pool=self,
  File "/usr/local/lib/python3.8/dist-packages/urllib3/util/retry.py", line 398, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='X.X.X.X', port=443): Max retries exceeded with url: /auth/admin.html (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1123)')))
```

The python scipt is the same you shared in your git:
```
from stormshield.sns.sslclient import SSLClient

client = SSLClient(
    host="X.X.X.X", port=443,
    user='admin', password='PASSWORD',
    sslverifyhost=False)

response = client.send_command("SYSTEM PROPERTY")

if response:
    model   = response.data['Result']['Model']
    version = response.data['Result']['Version']

    print("Model: {}".format(model))
    print("Firmware version: {}".format(version))
else:
    print("Command failed: {}".format(response.output))

client.disconnect()
```                     
Thanks for your help ! 
Best regards

**Comment by remip2** [comment]
If you have a custom certificate issued by a CA on your firewall, you can specify the certificate authority file with the `cabundle="/path_to/ca.pem"` parameter

For testing, you can also disable the check with `sslverifypeer=False`.

**Comment by halimB8** [comment]
Thanks for your reply @remip2, 
I tested it with `sslveritypeer=False` and I am not getting the certicate error anymore (as I am testing it in production firewall and as it's my first time doing it I gave a wrong password in the script  just to see if the python scipt try to connect to my firewall), but I got an error and In my firewall logs I didn't find any log of an authentication failed so I think that it couldn't even arrive to my firewall.  

```
Traceback (most recent call last):
  File "/usr/lib/python3.8/xml/etree/ElementTree.py", line 1693, in feed
    self.parser.Parse(data, 0)
xml.parsers.expat.ExpatError: syntax error: line 1, column 49

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/Stormshield_firewall/python-SNS-API/stormshield/sns/sslclient/__init__.py", line 399, in connect
    nws_node = ElementTree.fromstring(request.content)
  File "/usr/local/lib/python3.8/dist-packages/defusedxml-0.7.0rc1-py3.8.egg/defusedxml/common.py", line 133, in fromstring
    parser.feed(text)
  File "/usr/lib/python3.8/xml/etree/ElementTree.py", line 1695, in feed
    self._raiseerror(v)
  File "/usr/lib/python3.8/xml/etree/ElementTree.py", line 1602, in _raiseerror
    raise err
xml.etree.ElementTree.ParseError: syntax error: line 1, column 49

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test.py", line 3, in <module>
    client = SSLClient(
  File "/home/Stormshield_firewall/python-SNS-API/stormshield/sns/sslclient/__init__.py", line 366, in __init__
    self.connect()
  File "/home/Stormshield_firewall/python-SNS-API/stormshield/sns/sslclient/__init__.py", line 402, in connect
    raise AuthenticationError("Can't decode authentication result")
stormshield.sns.sslclient.AuthenticationError: Can't decode authentication result
```

Do You think that I am getting this error just cause it's the bad password even if I didn't get any log ? (knowing that when I test a wrong password in graphical interface of the firewall, I can see it in logs) 

Thanks again.

**Comment by remip2** [comment]
A bad password should raise:
stormshield.sns.sslclient.AuthenticationError: Authentication failed

You should check your webadmin ACL and validate API is available on this interface.

You can add debugging to have more info on the error:

```
from stormshield.sns.sslclient import SSLClient

import logging

logger = logging.getLogger()
logger.setLevel(logging.DEBUG)

logging.debug("Enable DEBUG")

client = SSLClient(
    host="10.60.3.6", port=443,
    user='admin', password='PASSWORD',
    sslverifyhost=False)

response = client.send_command("SYSTEM PROPERTY")

if response:
    model   = response.data['Result']['Model']
    version = response.data['Result']['Version']

    print("Model: {}".format(model))
    print("Firmware version: {}".format(version))
else:
    print("Command failed: {}".format(response.output))

client.disconnect()
```

**Comment by halimB8** [comment]
Thanks for your answers,

I tried the debug, and I am getting an error 405, Method not allowed

```
DEBUG:root:Enable DEBUG
INFO:root:Connecting to X.X.X.X on port 443 with user admin
DEBUG:root:<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<HTML><HEAD><TITLE>405 Method Not Allowed</TITLE></HEAD>
<BODY><H1>Method Not Allowed</H1></BODY></HTML>
Traceback (most recent call last):
  File "/usr/lib/python3.8/xml/etree/ElementTree.py", line 1693, in feed
    self.parser.Parse(data, 0)
xml.parsers.expat.ExpatError: syntax error: line 1, column 49

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/halim/Stormshield_firewall/python-SNS-API/stormshield/sns/sslclient/__init__.py", line 399, in connect
    nws_node = ElementTree.fromstring(request.content)
  File "/usr/local/lib/python3.8/dist-packages/defusedxml-0.7.0rc1-py3.8.egg/defusedxml/common.py", line 133, in fromstring
    parser.feed(text)
  File "/usr/lib/python3.8/xml/etree/ElementTree.py", line 1695, in feed
    self._raiseerror(v)
  File "/usr/lib/python3.8/xml/etree/ElementTree.py", line 1602, in _raiseerror
    raise err
xml.etree.ElementTree.ParseError: syntax error: line 1, column 49

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test.py", line 12, in <module>
    client = SSLClient(
  File "/home/halim/Stormshield_firewall/python-SNS-API/stormshield/sns/sslclient/__init__.py", line 366, in __init__
    self.connect()
  File "/home/halim/Stormshield_firewall/python-SNS-API/stormshield/sns/sslclient/__init__.py", line 402, in connect
    raise AuthenticationError("Can't decode authentication result")
stormshield.sns.sslclient.AuthenticationError: Can't decode authentication result

```

I will ask the admin to dig more in this error as I don't have the access to the firewall right now.
Thanks again :)
